// Downloads Gambarino + Supreme from Fontshare into public/fonts and writes fonts.css.
// Run once. Keeps the site free of any external request at runtime.
import fs from 'node:fs/promises';
import path from 'node:path';

const OUT = path.resolve('public/fonts');
await fs.mkdir(OUT, { recursive: true });

const REQ = ['gambarino@400', 'supreme@400,500,700'];
let css = '/* Self-hosted. Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n';

for (const q of REQ) {
  const res = await fetch(`https://api.fontshare.com/v2/css?f[]=${q}`, {
    headers: { 'User-Agent': 'Mozilla/5.0' },
  });
  if (!res.ok) throw new Error(`fontshare ${q}: ${res.status}`);
  let sheet = await res.text();

  const urls = [...sheet.matchAll(/url\('(\/\/cdn\.fontshare\.com\/[^']+\.woff2)'\)/g)];
  for (const [, u] of urls) {
    const name = u.split('/').pop();
    const bin = await fetch('https:' + u);
    if (!bin.ok) throw new Error(`font file ${name}: ${bin.status}`);
    await fs.writeFile(path.join(OUT, name), Buffer.from(await bin.arrayBuffer()));
    sheet = sheet.replaceAll(`'${u}'`, `'./fonts/${name}'`);
    console.log('saved', name);
  }

  // Drop the non-woff2 sources Fontshare lists after the woff2 one.
  sheet = sheet.replace(/,\s*url\('\/\/cdn\.fontshare\.com\/[^']+'\)\s*format\('(woff|truetype|opentype)'\)/g, '');
  css += '\n' + sheet.trim() + '\n';
}

css = css.replace(/font-display:\s*\w+;/g, 'font-display: swap;');
if (!css.includes('font-display')) css = css.replace(/(font-weight: \d+;)/g, '$1\n  font-display: swap;');

await fs.writeFile(path.resolve('public/fonts.css'), css, 'utf8');
console.log('wrote public/fonts.css');
